namespace: default 
GO_ENV: production

webserver:
  releaseName: webserver
  port: 5050
  type: NodePort
  nodePort: 31300
  host: example.com
  path: /
  pathType: Prefix

image:
  repository: docker-username/image-name
  tag: v1.0.0
  pullPolicy: Always

replicaCount: 1

api:
  port: 8080
  type: NodePort
  nodePort: 31301
  releaseName: api
  path: /api/
  pathType: ImplementationSpecific

database:
  name: LMWfitness
  user: postgres
  port: 5432
  type: ClusterIP
  sslMode: disable

storage:
  storageClass: standard

livenessProbe:
  initialDelaySeconds: 30
  timeoutSeconds: 5
  periodSeconds: 10
  failureThreshold: 3
readinessProbe:
  initialDelaySeconds: 15
  timeoutSeconds: 5
  periodSeconds: 10
  failureThreshold: 3