namespace: default 
GO_ENV: production

webserver:
  releaseName: webserver
  port: 5050
  type: NodePort
  nodePort: 31300
  host: example.com

image:
  repository: docker-username/image-name
  tag: v1.0.0
  pullPolicy: Always

replicaCount: 1

api:
  port: 8080
  type: NodePort
  nodePort: 31301
  releaseName: api

database:
  name: LMWfitness
  user: postgres
  port: 5432
  type: ClusterIP
  sslMode: disable

storage:
  storageClass: standard