apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-frontend-configmap
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Values.namespace }}
data:
  default.conf: |
    server {
          listen {{ .Values.webserver.port }};
          server_name _;
          error_log /var/log/nginx/error.log warn;

          location /api/ {
            proxy_pass http://{{ .Values.api.releaseName }}-backend-service:{{ .Values.api.port }}/;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
          }

          location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /index.html;
          }

          # Add error page
          error_page 500 502 503 504 /50x.html;
          location = /50x.html {
            root /usr/share/nginx/html;
          }
        }
