apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: lmwprac
spec:
  selector:
    app: backend
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
  type: ClusterIP
