apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: backend
  ports:
  - port: {{ .Values.api.port }}
    targetPort: {{ .Values.api.port }}
    protocol: TCP
  type: {{ .Values.api.type }}
