apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: lmwprac
spec:
  selector:
    app: frontend
  type: NodePort
  ports:
  - port: 5050
    targetPort: 5050
    nodePort: 31313
