apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name}}-postgres-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: postgres
  ports:
  - port: {{ .Values.database.port }}
    targetPort: {{ .Values.database.port }}
    protocol: TCP
  type: {{ .Values.database.type }}