apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: lmwprac
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
  type: ClusterIP