apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}-ingress
    meta.helm.sh/release-namespace: {{ .Values.namespace }}
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.webserver.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-frontend-service
            port:
              number: {{ .Values.webserver.port }}
      - path: /api
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Release.Name }}-backend-service
            port:
              number: {{ .Values.api.port }}