apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
  namespace: lmwprac
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: react-frontend-fitness-locator
    meta.helm.sh/release-namespace: lmwprac
data:
  default.conf: |
    upstream api {
      server backend-service:8081;
    }

    server {
      listen 5050;
      server_name _;
      error_log /var/log/nginx/error.log warn;

      location /api/ {
        proxy_pass http://backend-service:8081;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }

      location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
      }
    }
